In [10]:
#SPLIT THE DATASET INTO K SECTION AND CONSIDER ONE SECTION FOR TEST AND OTHER FOR TRAINING
#AND REPEAT THE PROCESS TILL ALL THE SECTIONS ARE CONSIDERED FOR TEST
#THEN WE TAKE AVG OF ALL CASES

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.datasets import load_digits

digits= load_digits()


In [11]:
X_train, X_test, y_train, y_test=train_test_split(digits.data , digits.target, test_size=0.2)


In [12]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.975

In [13]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [14]:
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9722222222222222

In [15]:
#THIS WAS MANUALYY, NOW WITH K-FOLD
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

#TO UNDERSTAND K-FOLD SPLIT
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
def get_score(model , x_train , x_test , y_train , y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [17]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold()

In [ ]:
score_lg =[]
score_svm = []
score_rf = []
# for train_index,test_index in kf.split(digits.data):
#   X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
#   score_lg.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
#   score_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
#   score_rf.append( get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))
# print(score_lg)
# print(score_svm)
# print(score_rf)

#THERE IS A SHORT WAY FOR ABOVE for loop
from sklearn.model_selection import cross_val_score
score_lg = cross_val_score(LogisticRegression(),digits.data,digits.target)
score_svm = cross_val_score(SVC(),digits.data,digits.target)
score_rf = cross_val_score(RandomForestClassifier(),digits.data,digits.target)
print(score_lg)
print(score_svm)
print(score_rf)